Fix encoding in JSON-LD template
The JSON-LD metadata was missing on pages where the description
contained ampersand (&) symbols.

This was accompanied by the following error:
freemarker.core._TemplateModelException: Error while invoking
the "headContribution" JSP custom tag; see cause exception

with the cause:
javax.servlet.jsp.JspException: org.xml.sax.SAXParseException;
lineNumber: 26; columnNumber: 101; The entity name must immediately
follow the '&' in the entity reference.